version: '2'
services:
  natsserver:
    image: nats
    ports:
      - "4222"
      - "7244"
      - "8222"
      - "6222"
    networks:
      default:
        aliases:
          - server.nats
  natscluster1:
    image: nats
    ports:
      - "4222"
      - "7244"
      - "8222"
      - "6222"
    networks:
      default:
        aliases:
          - cluster01.nats
    volumes:
      - /usr/local/nats-poc/gnatsd-A.conf:/tmp/cluster.conf
    command: -c /tmp/cluster.conf -p 4222 -D -V
  natscluster2:
    image: nats
    ports:
      - "4223"
      - "7246"
      - "8222"
      - "6222"
    networks:
      default:
        aliases:
          - cluster02.nats
    depends_on:
          - natscluster1
    volumes:
      - /usr/local/nats-poc/gnatsd-B.conf:/tmp/cluster.conf

    command: -c /tmp/cluster.conf -p 4223 -D -V
  natscluster3:
    image: nats
    ports:
      - "4224"
      - "7248"
      - "8222"
      - "6222"
    networks:
      default:
        aliases:
          - cluster03.nats
    depends_on:
      - natscluster1
      - natscluster2
    volumes:
      - /usr/local/nats-poc/gnatsd-C.conf:/tmp/cluster.conf
    command: -c /tmp/cluster.conf -p 4224 -D -V
  client:
    image: node:5.10.1
    networks:
      default:
        aliases:
          - client01
    volumes:
      - /root/misc/nats-rest-benchmark/client:/root/client
  proxy:
    image: node:5.10.1
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - proxy01
    volumes:
      - /root/misc/nats-rest-benchmark/proxy:/root/proxy
  service:
      image: node:5.10.1
      ports:
        - "3000:3000"
      networks:
        default:
          aliases:
            - service01
      volumes:
        - /root/misc/nats-rest-benchmark/service:/root/service
